//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TYPE]
        ///0.33:0.99:0.67
        ///0.18:0.99:0.63
        ///0.51:0.99:0.61
        ///0.73:0.99:0.76
        ///0.06:0.99:0.63
        ///0.99:0.99:0.66
        ///[SIZE]
        ///0.33:0.99:0.67
        ///0.18:0.99:0.68
        ///0.08:0.99:0.61
        ///0:0.99:0.69
        ///0.82:0.99:0.73
        ///0.71:0.99:0.66
        ///0.6:0.99:0.59
        ///0.54:0.99:0.65
        ///0.46:0.99:0.58
        ///[SUBREGION]
        ///[SU]
        ///0.46:0.99:0.99
        ///0.41:0.99:0.67
        ///[GW]
        ///0.46:0.99:0.99
        ///0.26:0.64:0.55
        ///[DS]
        ///0.46:0.99:0.99
        ///0.78:0.99:0.67
        ///[CC]
        ///0.46:0.99:0.99
        ///0.06:0.99:0.61
        ///[HI]
        ///0.46:0.99:0.99
        ///0.51:0.52:0.56
        ///[SI]
        ///0.46:0.99:0.99
        ///0.11:0.99:0.71
        ///0.91:0.99:0.75
        ///[SH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
